### PR TITLE
Update relationships.md

### PR DESCRIPTION
**Pull request by Lalithkumarponnambalam**
### **Update relationships.md content**
The following issue will be rectified:

- jhipster/generator-jhipster/issues/25584

I have referenced the "joint fields" from the JHipster Pro documentation. The correct link for the documentation is:

- [JHipster Pro Documentation - Relationships with Joint Fields](http://www.jhipster.pro/docs/jdl/relationships.en#with-joint-fields)

### CODE REVIEW

**Comment by OmarHawk** [comment]
Is this correct? To me the described syntax rather means "show name in any referencing attribute, like dropdown or list view link", the join will still always be executed based on the foreign key relationship afaik.

**Comment by Lalithkumarponnambalam** [comment]
@OmarHawk  yes this is correct. In the JHipster Pro Documentation, there is an explanation of join fields in relationships, which can be found at the following link: [JHipster Pro Documentation - Relationships with Joint Fields](http://www.jhipster.pro/docs/jdl/relationships.en#with-joint-fields).

**Comment by OmarHawk** [comment]
Still not convinced. We are using the syntax and it works as **I did** describe. See also the syntax description here: https://www.jhipster.tech/jdl/relationships#syntax ---> `<display field>`

Also the .pro site looks kind of unofficial and rather outdated.

**Comment by mshima** [comment]
That’s not correct.
```
relationship OneToOne {
  A{b(name)} to B{a(name)}
}
```

means that when showing A, B will have `b.name` field as label (instead of b.id) in the frontend. Same for B.
joins always use ids.

**Comment by mraible** [comment]
We updated the website with a new design. Can you please update this issue accordingly?

**Comment by mraible** [comment]
Closing due to lack of response.

**Pull request closed without merging**
