### PR TITLE
add back updated QueryDSL tip for gradle project

### PR DESCRIPTION
**Pull request by arnaud-deprez**
Sorry for the time I took for this, I was very busy :)

### CODE REVIEW

**Comment by arnaud-deprez** [comment]
Btw, I can't serve jekyll files: 

```sh
⇒  bundle exec jekyll serve 
Configuration file: /Users/arnaud/Development/my/java/jhipster.github.io/_config.yml
Configuration file: /Users/arnaud/Development/my/java/jhipster.github.io/_config.yml
            Source: /Users/arnaud/Development/my/java/jhipster.github.io
       Destination: /Users/arnaud/Development/my/java/jhipster.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  **Liquid Exception: invalid byte sequence in US-ASCII in _layouts/redirect.html**
jekyll 3.4.3 | Error:  invalid byte sequence in US-ASCII
```
Any idea ? I'm not familiar with jekyll

**Comment by jdubois** [comment]
Don't worry for Jekyll, I'll test this myself.
Too bad we now miss the Maven config, as this is what most people are using :-(

**Comment by arnaud-deprez** [comment]
But for maven, there is still a link to QueryDSL official documentation where it's well documented.
I can put back what @omrzljak did but it's not in the official documentation and I didn't take the time to test it.

**Comment by jdubois** [comment]
OK I'm merging this, and testing later :-)

**Pull request merged**
