### PR TITLE
Added section about yarn, yarn.lock and yarn cache. Requested by http…

### PR DESCRIPTION
**Pull request by Zacorich**
…s://github.com/jhipster/generator-jhipster/issues/5362#issuecomment-284175620

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Following the docs https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-force

Did you try `yarn install --force` ?
> This refetches all packages, even ones that were previously installed.

**Comment by Zacorich** [comment]
For my particular case solution was to regenerate yarn.lock file so I didn't try to re-fetch packages after I solved the issue. I just added more info about yarn to jhipster website for people to pay attention to yarn internal work and be aware of what can go wrong and where to look.

**Comment by PierreBesson** [comment]
@Zacorich Is it possible to rework the phrasing a little. The point you make here is interesting but your sentences are too long, they should be broken down in small chunks.

**Comment by jdubois** [comment]
@PierreBesson is right, I'm not merging this as is, for 2 reasons:

- There are some formatting issues, like missing upper cases (`Yarn` not `yarn`), etc... And indeed the sentences are too long
- We usually don't document third-party tools: here you give hints on how to use Yarn, and this isn't specific to JHipster

Then, I understand this would help many people, but we need to rework this. I'll have a look when I have time.

**Comment by jdubois** [comment]
I have heavily modified your text, and I'm merging this, thanks!

**Pull request merged**
