### PR TITLE
Add showcase page

### PR DESCRIPTION
**Pull request by deepu105**
Adds a showcase page
image

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois plz take a look. Doesnt have any unreleased feature info so can be directly merged

**Comment by deepu105** [comment]
@jdubois are you ok with this?

**Comment by jdubois** [comment]
Yes, but I'd like to have more showcases, I'll try to find some tomorrow

**Comment by pascalgrimaud** [comment]
https://sportsbooth.tv/ from @ruddell right ?

**Comment by pascalgrimaud** [comment]
https://www.pwnwin.com/ : if I remember well, I saw it from Tweeter or somewhere else

**Comment by jdubois** [comment]
Argh did you also update the presentation? I thought you forgot about it, and I just updated it 1 hour ago!!!!!

**Comment by deepu105** [comment]
Nope I didn't :) but its ok

Thanks & regards,
Deepu

**Comment by alfredorueda** [comment]
We are preparing a new improved version of the video to showcase advanced features of SoundXtream. The new version of the video will be ready at the end of the week. 😀😀

**Comment by alfredorueda** [comment]
http://www.bluemagiccat.com it's also very hipster 😄 

Natán is developing a very cool video demonstrating the features of this booking catamaran service app 😀

Thanks guys! 
JHipster is great! Thank you very much you rock

**Comment by alfredorueda** [comment]
https://www.pwnwin.com/ is very cool!!!! :-)

**Comment by deepu105** [comment]
@jdubois moved other changes to a new PR #399 so please squash this when merging coz the commit hsitory looks ugly. I couldnt do it from my branch

**Comment by jdubois** [comment]
I merged this, but the screenshots do not show up :-(

**Comment by deepu105** [comment]
The iframed content was with http thats why I guess. Will update them to https

**Comment by deepu105** [comment]
Or better I will just use screenshots instead of iframed sites as some sites will not have https. I'll fix it today

**Comment by deepu105** [comment]
Its fixed

**Pull request merged**
