### PR TITLE
Add new Spring social connector Tip

### PR DESCRIPTION
**Pull request by moifort**
Little tutorial to explain how to add a Spring connector.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@moifort : maybe can you do it as a module ? I think it is doable

**Comment by moifort** [comment]
Hahahah! yes I was working on it!

**Comment by pascalgrimaud** [comment]
I know it ! Waiting your repo :octocat:

**Comment by tayfunyasar** [comment]
I'm going to cry. It looks awesome! This is the medicine im looking for ^^

**Pull request merged**
