### PR TITLE
added trainings link to Rapid app development using JHipster course

### PR DESCRIPTION
**Pull request by subbaraja**
added trainings link to Rapid app development using JHipster course

### CODE REVIEW

**Comment by jdubois** [comment]
Usually we only put on the front page material that we have reviewed, so I would like first to have a few people from the core team have a look at the course.
I would very happily do it under normal circumstances, of course...
@pascalgrimaud are there people in your team at Ippon who could check this out?

**Comment by pascalgrimaud** [comment]
@jdubois : yes, I'll ask it tomorrow

**Comment by SudharakaP** [comment]
I've taken a look at some of the videos and the site in general. Some points I have to highlight; hope I am not too critical on this one. :smile:  

1) The site seems to have a certificate problem; both on Firefox and Chrome I get the warning that the site is not fully secure.

2) The UI to access the courses isn't simple. When I go to the course page and click on the `Contents` link at the bottom of the course, I can see the video titles but clicking them won't play them. Only the introductory video can be played. So I clicked on the `Play Course` button which gave me an option to `Sign In` or `Register`. After I registered and logged in, I still had to add the course to the cart and buy it (it's zero dollars) in order to access the other videos. Overall I think it isn't a user friendly process.
 
3) Some videos have sound issues; either the sound is not equalized (so I have to move my volume up or down when going from one video to another) or there's no sound at all (such as the videos titled `update kubernetes script with secrete` and `create docker repo`).

4) I think there's some videos which aren't playable at all; such as `application config` and `UI Themes`. 

5) The website accepts passwords such as "test" which I think isn't a great idea.

6) I see a lot of typos or inconsistencies in the website overall as well.

I am not sure this website warrants a place in the front page at its current state. I haven't looked at the course content yet; maybe someone else could chip in on that. :smile:

**Comment by subbaraja** [comment]
Hi Sudharaka,
Thank you for your comments, I appreciate your help.    The site is in beta, we will add a note on the website so that users can expect few improvements with the user interface.
Here response to your comments:
1) Yes, we have already added a certificate and enabled https, still, the browser shows as not fully secured.  This is a known issue and will fix it.
2)  All the courses are subscription-based.   We fix the UI so that the user will get the "Play" button only if he/she is subscribed to the course.
3) We will fix videos with "No sound".  We are aware of it with one or two videos and it is on our TODO list.  
4) One or two lessons are place holders as of now.  We are fixing them as we speak.
5) We will add a few more validation cases to the password field.
ThanksSubbaraja

    On Monday, 30 March, 2020, 05:34:35 am IST, Sudharaka Palamakumbura <notifications@github.com> wrote:  
 
 


I've taken a look at some of the videos and the site in general. Some points I have to highlight; hope I am not too critical on this one. 😄
    
   -    
The site seems to have a certificate problem; both on Firefox and Chrome I get the warning that the site is not fully secure.

   -    
The UI to access the courses isn't simple. When I go to the course page and click on the Contents link at the bottom of the course, I can see the video titles but clicking them won't play them. Only the introductory video can be played. So I clicked on the Play Course button which gave me an option to Sign In or Register. After I registered and logged in, I still had to add the course to the cart and buy it (it's zero dollars) in order to access the other videos. Overall I think it isn't a user friendly process.

   -    
Some videos have sound issues; either the sound is not equalized (so I have to move my volume up or down when going from one video to another) or there's no sound at all (such as the videos titled update kubernetes script with secrete and create docker repo).

   -    
I think there's some videos which aren't playable at all; such as application config and UI Themes.

   -    
The website accepts passwords such as "test" which I think isn't a great idea.

   -    
I see a lot of typos or inconsistencies in the website overall as well.


I am not sure this website warrants a place in the front page at its current state. I haven't looked at the course content yet; maybe someone else could chip in on that. 😄

**Comment by PierreBesson** [comment]
@subbaraja First congrats on releasing your own training videos about JHipster on a website developed with JHipster itself ! I'm impressed, even though it still looks kind of rough, I assume it was quick to develop.
Personally I don't have a problem to add a link to your website if the following conditions are met:
- The list of videos can be seen without first logging in.
- No certificate errors / clean UI / UX to start the video
- More review of the content by the JHipster core team is needed.

**Comment by subbaraja** [comment]
Thanks @PierreBesson.  Trainings.com is a marketplace for video courses, still it in beta and we can expect more UI/UX changes soon.   Regarding your comment#1, by design access to the full course is restricted to only subscribed users.  The workflow remains the same, users should select the course --> add to cart --> and subscribe to view the full course.  By the way, I hope we should be worried more about the course content than the workflow which is totally internal to our company?

**Comment by subbaraja** [comment]
@PierreBesson @SudharakaP @jdubois @pascalgrimaud @avdev4j -- friends - firstly thank you for your time and looking at this course.   Let me give our word - first, we are working on to set up https and ordered an EV or digital certificate for our website.  Second - we will continuously work to fix and refine the content until this comes out super good and super value for our audience.   Third - We are working on two full-length video courses that focus on reference implementations of full-stack applications based on JHipster/Spring/Angular/Premium Components, etc.

I just wanted to keep you posted so that we are on the same page.  

Thanks.
Subbaraja

**Comment by subbaraja** [comment]
Thanks @SudharakaP, @PierreBesson and all.  The certificate issue is now resolved and the course is now available for subscribed users for free.   We continue to fix video content to help our users.  Thanks!

**Comment by PierreBesson** [comment]
This looks fine to me. Thank you @subbaraja.

**Pull request merged**
