### PR TITLE
Update docker-compose commands

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/2600

### CODE REVIEW

**Comment by jdubois** [comment]
I'm waiting for our next release to merge this, so the documentation matches the release!

**Comment by deepu105** [comment]
@pascalgrimaud may you should update it in the redesigned site as well so that we dont miss it

**Comment by pascalgrimaud** [comment]
Ok @deepu105, I will do it tonight

**Comment by pascalgrimaud** [comment]
No need this PR anymore

**Pull request closed without merging**
