### PR TITLE
add micronaut family member to artwork page

### PR DESCRIPTION
**Pull request by atomfrede**
This adds the micronaut family member to the artwork page. I can't find the files in the local repository I guess there is a redirect/configuration to our artwork repo somewhere, is that correct?

### CODE REVIEW

**Comment by jdubois** [comment]
@atomfrede yes there's a redirect

**Comment by jdubois** [comment]
Argh the size is not the same as the other images:
Screenshot 2020-10-01 at 14 12 19

**Comment by jdubois** [comment]
As the size wasn't correct I reverted it in #1013

**Comment by atomfrede** [comment]
Seen it too 😅

**Comment by jdubois** [comment]
It's just sample images, honestly no need to spend much time on this

**Pull request merged**
