### PR TITLE
added jhipster ide

### PR DESCRIPTION
**Pull request by colameo**

### CODE REVIEW

**Comment by colameo** [comment]
please feel free to adapt and change content

**Comment by jdubois** [comment]
Thanks: I'll change some of the content, I hope that will be fine with you

And I'll add this to the menu on the left, of course!

**Comment by jdubois** [comment]
I'm keeping the "eclipse2.gif" file but it is not used, shouldn't it be removed?

**Comment by jdubois** [comment]
And for this to work, I need to remove your "gh" branch -> I'm doing it, I hope it's OK for you

**Comment by jdubois** [comment]
Oh, I just needed to disable Github pages, so no worries!

**Comment by colameo** [comment]
@jdubois the eclipse2.gif is actually the optimized version from @PierreBesson, so maybe it's better to use that one. I've spoken to @jbadeau this morning and he will make a nicer page with more content.
BTW, @cbornet will also add an installation guide (or a screen cast) about the visual studio code extension. Thanks for publishing it!

**Comment by jdubois** [comment]
OK, can you replace the image then? And add content, modify, etc, like you feel like -> then it's just a PR and I'll merge this very quickly

**Pull request merged**
