### PR TITLE
wrong example

### PR DESCRIPTION
**Pull request by wanghengxn**
Can't reproduce

```jdl
entity A {
    name String
}
entity B {
    name String
}

relationship OneToOne {
  A{a(name)} to B{b(name)}
}
```

### CODE REVIEW

**Comment by wanghengxn** [comment]
```java
public class A {
    @Column(name = "name")
    private String name;

    @OneToOne
    @JoinColumn(unique = true)
    private B a;
}
```
```java
pubic class B {
    @Column(name = "name")
    private String name;

    @OneToOne(mappedBy = "a")
    @JsonIgnore
    private A b;
}
```
```xml
<addForeignKeyConstraint baseColumnNames="aa_id"
                                 baseTableName="a"
                                 constraintName="fk_aa_aa_id"
                                 referencedColumnNames="id"
                                 referencedTableName="b"/>
```

**Comment by jdubois** [comment]
I'm sorry I don't understand why this example is wrong?

**Comment by jdubois** [comment]
@MathieuAA there are 3 tickets created by @wanghengxn on the JDL, can you have a look at them? I'm assigning them to you

**Comment by MathieuAA** [comment]
alright

**Comment by jdubois** [comment]
Thanks! As the JDL is very important, adding a $200 bug bounty for you to share ($100 each)

**Review by mshima — APPROVED** [review]
```
relationship OneToOne {
  A{b(name)} to B{a(name)}
}
```
Both names actually are shown at the ui, not the join.

**Comment by MathieuAA** [comment]
I don't get it. @mshima can you explain the issue here?

**Comment by mshima** [comment]
The `(name)` is the display name like it's explained above in the same page and populates the `otherEntityField` property.

`otherEntityField` is used as label to the registry in the frontend.
Example:
```
entity Colaborator {
  username String unique
}

entity Issue {}

relationship ManyToOne {
  Issue{reporter(username)} to Colaborator
}
```

With records 
```
id:1000, username:MathieuAA
id:1001, username:mshima
```

Will show username MathieuAA and mshima in the frontend at Issue pages (selects and views) instead of showing the id.

There is no change in the sql.

**Comment by MathieuAA** [comment]
Ok, to sum up, and don't hesitate to correct me if I'm wrong, there's an issue in the generated code?

**Comment by mshima** [comment]
> Ok, to sum up, and don't hesitate to correct me if I'm wrong, there's an issue in the generated code?

I don't think so, I don't recall a different behavior from what I described.
IMO the PR is correct.

**Comment by MathieuAA** [comment]
@mshima I could have sworn this has changed... anyway, as the current behavior fits what's proposed here, let's merge it. Thanks!
@wanghengxn thanks! (you guys can have the bounty)

**Review by MathieuAA — APPROVED** [review]

**Comment by wanghengxn** [comment]
> @mshima I could have sworn this has changed... anyway, as the current behavior fits what's proposed here, let's merge it. Thanks!
> @wanghengxn thanks! (you guys can have the bounty)

Thanks！ :) 
How can I get the bounty. My PayPal account is jmch03@126.com.

**Comment by jdubois** [comment]
@wanghengxn have a look at https://www.jhipster.tech/bug-bounties/ we've been doing this for several years and it works great.

**Comment by wanghengxn** [comment]
Hi, I have submitted my OpenCollective expense, and the link is https://opencollective.com/generator-jhipster/expenses/48854

**Comment by jdubois** [comment]
Thanks, it is approved! Thank you for helping on the JDL, that's hugely important

**Comment by mshima** [comment]
Since my reviewing was actually helpful, half bounty claimed https://opencollective.com/generator-jhipster/expenses/50251.

**Comment by pascalgrimaud** [comment]
@mshima : approved

**Pull request merged**
