### PR TITLE
Update official blueprint with correct publishing

### PR DESCRIPTION
**Pull request by amanganiello90**
Rename section with correct blueprint order

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks @amanganiello90 !

**Comment by amanganiello90** [comment]
thanks a lot @jdubois! .. next days I will release the first version of the node.js blueprint :)

**Comment by jdubois** [comment]
Oh please don't hesitate to mention @java_hipster on Twitter, so I can inform everyone as soon as it's ready (and congratulate you publicly, of course!!)

@deepu105 @pascalgrimaud shouldn't we give some bug bounty to the NodeJS blueprint?? I don't remember we have anything?

**Comment by pascalgrimaud** [comment]
As far as I remember, I don't think so
So yes, we should give some bug bounty for this blueprint

**Comment by jdubois** [comment]
Thanks @pascalgrimaud 
@amanganiello90 I added the "bug bounty" labels to your repo -> Please create a ticket for the release, and I'll add a bounty to it, so you can claim it! (and please don't hesitate to notify me!! I get so many GitHub emails that I might miss it)

**Comment by amanganiello90** [comment]
Thanks a lot @pascalgrimaud, @jdubois and @deepu105.. Only a question... Could you please tell me what is a "bug bounty" on a github repo? I don't know that, excuse me :)

**Comment by jdubois** [comment]
LOL @amanganiello90 I hope you'll like the concept: https://www.jhipster.tech/bug-bounties/

**Pull request merged**
