### PR TITLE
Small performance improvements on mobile devices

### PR DESCRIPTION
**Pull request by SvMak**
- replaced hero image from svg to webp;
- reducing DOM size.

Related to https://github.com/jhipster/generator-jhipster/issues/27122

### CODE REVIEW

**Comment by mraible** [comment]
I tried running the current site through https://pagespeed.web.dev:

Screenshot 2024-09-12 at 18 26 42

Then, I tried the preview for this PR:

Screenshot 2024-09-12 at 18 27 36

I'm not sure why the SEO went down. Maybe PageSpeed gets different information from Netlify vs. GitHub pages?

**Comment by SvMak** [comment]
Screenshot 2024-09-13 073004

Netlify is set to noindex

**Comment by mraible** [comment]
The main image on the homepage looks a little grainy with this PR. The current site has a much more crisp image, at least on my MacBook Pro.

**Comment by SvMak** [comment]
> The main image on the homepage looks a little grainy with this PR. The current site has a much more crisp image, at least on my MacBook Pro.

@mraible Could you please check the latest changes?

**Comment by mraible** [comment]
The image looks better. Performance is 51 on mobile and 70 on desktop. 

https://pagespeed.web.dev/analysis/https-deploy-preview-1382--jhipster-site-netlify-app/oatghbq1ev?form_factor=mobile

I was going to test our documentation archives to see what the old site's performance was. That's when I discovered our documentation archives are still using files from the main site. For example, see https://www.jhipster.tech/documentation-archive/v8.7.0/. 

I've entered a new issue to track this. https://github.com/jhipster/generator-jhipster/issues/27315

**Comment by SvMak** [comment]
> The image looks better. Performance is 51 on mobile and 70 on desktop.
> 
> https://pagespeed.web.dev/analysis/https-deploy-preview-1382--jhipster-site-netlify-app/oatghbq1ev?form_factor=mobile

In preview mode Netlify added some third party scripts and this lowered the rating, in production version the rating should be higher.

**Review by mraible — APPROVED** [review]

**Pull request merged**
