### PR TITLE
Replace Twitter by X

### PR DESCRIPTION
**Pull request by qmonmert**
@mraible @jdubois @pascalgrimaud @DanielFran are you ok with this update?

I didn't update Twitter logo because the X Twitter is not available with font-awesome 4, we need to upgrade to 6 (with a lot of work).

There are only two logos:
image
image

### CODE REVIEW

**Comment by mraible** [comment]
I still prefer to call it Twitter.

**Comment by pascalgrimaud** [comment]
I don't think we need to update old release notes
We could update the current main pages, and that's all

**Comment by qmonmert** [comment]
@pascalgrimaud these 4 files or just `index.html`?
image

**Comment by pascalgrimaud** [comment]
Yes I think @qmonmert

**Comment by qmonmert** [comment]
@pascalgrimaud I updated with this solution.

@mraible WDYT about this?

**Comment by mraible** [comment]
@qmonmert I don't feel strongly enough about it to approve or deny. ;)

**Comment by qmonmert** [comment]
Ok I close this PR

**Pull request closed without merging**
