### PR TITLE
Added Deploying to AWS with Boxfuse section

### PR DESCRIPTION
**Pull request by axelfontaine**
Please let me know if you want anything added or changed.

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks @axelfontaine - at first sight it looks OK, I'll read everything (for typos etc....) before merging, but that should be quick

**Comment by jdubois** [comment]
I'll just rewrite the titles -> "AWS with Beanstalk" is just too long on our menu... So I'll keep "AWS" as before (as Beanstalk is the "normal" AWS), and rename your page "Deploying with Boxfuse"

**Comment by axelfontaine** [comment]
Thank you Julien. The reason I added AWS with Beanstalk is that "normal" AWS can now mean CodeDeploy, CodePipeline, Beanstalk or OpsWorks! The number of different ways they offer to solve the same problem is really staggering and this just helped clarify the one being used here.

**Comment by jdubois** [comment]
Yes I kept it on the main page, but on the left menu that's just too long

**Comment by axelfontaine** [comment]
Would you be OK with a quick PR that cross references both?

Something like this (+links of course):

On the Boxfuse page: 

> As an alternative to Boxfuse you can also deploy your JHipster application to AWS using Beanstalk

On the Beanstalk page:

> As an alternative to Beanstalk you can also deploy your JHipster application to AWS using Boxfuse

**Comment by jdubois** [comment]
Yes -> don't hesitate to advertise for Boxfuse! You provide full JHipster support, AWS doesn't!

**Pull request merged**
