### PR TITLE
improve karma browser docs

### PR DESCRIPTION
**Pull request by PierreBesson**
linked to https://github.com/jhipster/generator-jhipster/pull/6623

### CODE REVIEW

**Comment by jdubois** [comment]
@PierreBesson sorry I totally forgot to merge this - as we switched back to PhantomJS, what do we do with this PR?

**Comment by PierreBesson** [comment]
I will rewrite this to explain how to set up chrome/Firefox headless instead.

**Comment by PierreBesson** [comment]
@jdubois done.

**Comment by jdubois** [comment]
Perfect!

**Pull request merged**
