### PR TITLE
bootswatch tip update

### PR DESCRIPTION
**Pull request by deepu105**
fix https://github.com/jhipster/generator-jhipster/issues/2554#issuecomment-168307642

### CODE REVIEW

**Comment by jdubois** [comment]
I can't test this right now, but I'm not sure this is valid Github Markdown.
For testing I installed Jekyll following the instructions from Github Pages.

**Comment by deepu105** [comment]
as per github markdown documentation this is valid
https://guides.github.com/features/mastering-markdown/

On Sat, Jan 2, 2016 at 10:48 PM, Julien Dubois <notifications@github.com>
wrote:

> I can't test this right now, but I'm not sure this is valid Github
> Markdown.
> For testing I installed Jekyll following the instructions from Github
> Pages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/jhipster.github.io/pull/153#issuecomment-168396811>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by jdubois** [comment]
Looks broken on my phone :-(

**Comment by deepu105** [comment]
Yes definitely broken, plz revert it, may be github pages doesnt support
github markdown completely, any idea how to make it render the {{ }}

**Comment by jdubois** [comment]
@deepu105 it's reverted!

**Pull request merged**
