### PR TITLE
Update upgrading_an_app.md

### PR DESCRIPTION
**Pull request by zhyd1997**
Fixes https://github.com/jhipster/generator-jhipster/issues/18097

### CODE REVIEW

**Comment by zhyd1997** [comment]
@mraible PTAL

**Comment by zhyd1997** [comment]
[$300 bug bounty claimed on the JHipster OpenCollective](https://opencollective.com/generator-jhipster/expenses/68315)

**Comment by pascalgrimaud** [comment]
@zhyd1997 : I'm waiting the review from @mraible and the merge, before approving the bounty :-)

**Comment by zhyd1997** [comment]
@pascalgrimaud 
Sure that 🙂
Me too!

**Review by mraible — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
@zhyd1997 : approved, thanks for your work :-)

**Pull request merged**
