### PR TITLE
Removed last occurences of the 'for' keyword

### PR DESCRIPTION
**Pull request by MathieuAA**

### CODE REVIEW

**Comment by MathieuAA** [comment]
Thanks Deepu!

**Comment by deepu105** [comment]
Don't forget to claim the bounty

**Comment by MathieuAA** [comment]
@deepu105 just for that? I'd rather let someone do a more substantial work :) There wasn't any real issue that wasn't fixed before

**Comment by deepu105** [comment]
Oh, you have done more than substantial work man, so I would gladly let you
claim it if you wish so. But it's up to you. If you do not want to claim it
then let me know of any issue that you would like me to assign that to.

Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
There was this very old PR about using the JDL to "replace" liquibase somehow (don't remember the details though). This, is definitely something worth a bounty.

**Pull request merged**
