### PR TITLE
Add GitHub-style links to headers

### PR DESCRIPTION
**Pull request by mraible**
Depends on https://github.com/jhipster/jhipster.github.io/pull/1161

### CODE REVIEW

**Comment by mraible** [comment]
For a preview, see https://github.com/mraible/jhipster.github.io/pull/3

**Comment by mraible** [comment]
Netlify preview is not working. Can someone please clone my repo/branch and test/approve?

```
git clone -b links-on-headings git@github.com:mraible/jhipster.github.io.git
cd jhipster.github.io
npm i
npm start
```

**Comment by mraible** [comment]
Seeing if open/close creates a Netlify preview. Please ignore.

**Comment by pascalgrimaud** [comment]
I'll test and merge it after the release, as it is not mandatory to have it for the new release

**Comment by pascalgrimaud** [comment]
@mraible : can you fix the conflict plz, so it can be merged

**Comment by mraible** [comment]
@pascalgrimaud Done.

**Comment by pascalgrimaud** [comment]
Thanks ! So with this PR, it should fix the deployment to Netifly

**Comment by mraible** [comment]
When I first loaded up jhipster.tech after this change, it showed the anchor link at the end of each header. When I hit Shift+Reload, it fixed the problem. Is there any way to expire the cache so this doesn't happen to others?

**Comment by pascalgrimaud** [comment]
I don't know.
Maybe @deepu105 ?

**Pull request merged**
