### PR TITLE
join climate strike

### PR DESCRIPTION
**Pull request by deepu105**
Discussion here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jhipster-dev/tj4sVWbv_Lw

### CODE REVIEW

**Comment by jdubois** [comment]
- I've just tested it and it works fine today. But how will it work on September, 20th, is there a way to test this?
- We should not merge it if we do a release before September, 20th, or people will have the banner forever in the archive - I don't think we have anything planned, but I feel like it's a bit dangerous to merge it too soon. @deepu105 @pascalgrimaud what do you think about this?

**Comment by deepu105** [comment]
@jdubois there is param which when enabled will show the actual screen. I have tested that and works well. The code automatically switches to that view on September 20

But yes we can merge this few days before 20th

**Comment by jdubois** [comment]
OK, then let's merge this a few days before. Perfect!

**Comment by pascalgrimaud** [comment]
Agree, feel free to merge this

**Comment by deepu105** [comment]
@jdubois @pascalgrimaud lets merge this after 6.3.0 release, I thinking of mentioning about it in my codeOne talk next week

**Comment by jdubois** [comment]
Yes +1

**Comment by pascalgrimaud** [comment]
+1

**Pull request merged**
