### PR TITLE
Add port information for SonarQube and Swagger

### PR DESCRIPTION
**Pull request by vivekmore**
- SonarQube
- Swagger Editor

### CODE REVIEW

**Review by atomfrede — APPROVED** [review]

**Comment by vivekmore** [comment]
@atomfrede - could this PR be merged?
unless there is something you'd like me to add to it?

**Comment by atomfrede** [comment]
Oh sorry totally forgot it. Let's merge it.

**Comment by vivekmore** [comment]
> Oh sorry totally forgot it. Let's merge it.

Ok cool. I'm not on the JHipster team so you'll have to help me out here :)

**Comment by atomfrede** [comment]
Will do. Couldn't do it from my mobile phone :phone:

**Pull request merged**
