### PR TITLE
update team page

### PR DESCRIPTION
**Pull request by deepu105**
a better looking team page :joy: 
@jhipster/developers guys take look
image

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
lol @deepu105 !

**Comment by cbornet** [comment]
Wow ! My photo is so ugly ! I really need to update that !

**Comment by atomfrede** [comment]
Looks pretty cool.

**Comment by deepu105** [comment]
ha ha Im reading the github avatars :+1:

**Comment by deepu105** [comment]
@atomfrede I guess you are the one who asked for a better team page  originally

**Comment by jdubois** [comment]
Great! I'm merging this!

**Comment by jdubois** [comment]
@deepu105 there's a small glitch, after Gaël, there a new line

**Comment by deepu105** [comment]
@jdubois Im not seeing it, which browser are you using

**Comment by deepu105** [comment]
oh ok got it wait ill fix it with a PR

**Comment by deepu105** [comment]
https://github.com/jhipster/jhipster.github.io/pull/184 this should fix it

**Pull request merged**
