### PR TITLE
make npmsearch protocol safe

### PR DESCRIPTION
**Pull request by deepu105**
it was a silly protocol issue, in mobile we were doing http i guess mostly
fix https://github.com/jhipster/generator-jhipster/issues/2762

### CODE REVIEW

**Comment by jdubois** [comment]
I merged it but I still have the issue... Maybe the page is taking time to build.

**Comment by deepu105** [comment]
Normally takes few seconds

**Comment by jdubois** [comment]
No, it's still broken

**Comment by deepu105** [comment]
Are you sure, its not from cache or something works for me

**Comment by deepu105** [comment]
Are u on android or ios?

@jhipster/developers can someone check if this works in mobile. 

The issue was coz of doing https from http site, so i changed to relative protocol

**Comment by atomfrede** [comment]
Works for me on Android with chrome.

**Comment by pascalgrimaud** [comment]
same, OK on android with chrome

**Comment by jdubois** [comment]
I'm sorry but this is still broken on my phone

**Comment by gmarziou** [comment]
@jdubois are you using default browser or Chrome?

**Comment by gmarziou** [comment]
Works for me on iOS Safari

**Comment by jdubois** [comment]
Default browser on the latest Android version on a Nexus 5.
Same issue in 4G and Wi-Fi

**Comment by deepu105** [comment]
My wife has nexus 5 ill check on that. I guess default on nexus is chrome
right.

It works in my samsung mobile and tablet - chrome, firefox and stock webkit

**Comment by jdubois** [comment]
It's OK I just tested again and it's working now!

**Comment by deepu105** [comment]
anyways im pushing another PR to use protocol from windows.location rather
than using just `//` to make sure of it

Thanks & Regards,
Deepu

**Pull request merged**
