### PR TITLE
updated mongock link and removed obsolete information

### PR DESCRIPTION
**Pull request by dieppa**
### Changes
- Updated mongock link to Mongock page
- Removed obsolete information about Mongo Atlas error, as it shouldn't happen with Mongock
- Removed obsolete information about the intention of replacing Mongobee with Mongock, as it's already replaced

### CODE REVIEW

**Review by murdos — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
I think it should target main branch, the jhipster7 branch is out dated

**Comment by murdos** [comment]
In this specific case, the jhipster_7 branch has more recent information than main: https://github.com/jhipster/jhipster.github.io/pull/1071

See https://github.com/jhipster/jhipster.github.io/pull/1086 too.
So what's the purpose of the jhipster_7 branch? If it's outdated, it should be merged and removed IMO. Otherwise it's really confusing.

**Comment by dieppa** [comment]
Thanks guys. Let me know, if so I can leave this one, or close it and reopen my other PR.

On the other hand, the release note, for the next beta(or maybe the already published, [7.0.0-beta.0](https://www.jhipster.tech/2020/12/21/jhipster-release-7.0.0-beta.0.html) and [7.0.0-beta.1](https://www.jhipster.tech/2021/01/17/jhipster-release-7.0.0-beta.1.html) ), should reflect the addition of Mongock?

I could add that to my PR too.

**Comment by pascalgrimaud** [comment]
Ok, no worry, I'll take care of it, before the next release :)

**Comment by pascalgrimaud** [comment]
I cherry pick the commit into prepare-jhipster-v7.0.0 branch

**Pull request closed without merging**
