### PR TITLE
Updates and polish

### PR DESCRIPTION
**Pull request by deepu105**
Polish presentation
Improve home page
Angular 2 updates
Some tweaks and fixes

Showacase page removed as it will be another PR

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois this can be merged immediately. Check if its ok for you

**Comment by jdubois** [comment]
I'm sorry there are conflicts on this page - and I'm not really sure what's happening, so many changes here, are you sure?

**Comment by deepu105** [comment]
Are you ok with the content? Ill fix conflicts and merge if you are ok

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Will open a new PR as this one is very dirty

**Pull request closed without merging**
