### PR TITLE
Add 6 new bronze sponsors

### PR DESCRIPTION
**Pull request by pascalgrimaud**
- Crosswordsolver
- Edusson
- Fair Laan
- MatchBanker.pl
- MatchBanker.no
- SuperKredit

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I think I was doing something wrong with the size of the image

**Comment by jdubois** [comment]
Thanks a lot @pascalgrimaud !
Also the pirate bay stopped sponsoring us, but they were doing it twice, so they still do it once (so weird!!!).
And can you add those sponsors to the readme in jhipster/generator-jhipster?
I'll do the tweets next week.

**Comment by pascalgrimaud** [comment]
@jdubois : yes I already prepared the PR for generator-jhipster but the size is not correct. I'm trying to fix it with gimp :D

**Comment by pascalgrimaud** [comment]
@jdubois : The Pirate Bay sponsored us the 19/10/2019, so for me, they are still bronze sponsor.

**Pull request merged**
