### PR TITLE
Update OIDC docs for JHipster 6

### PR DESCRIPTION
**Pull request by mraible**
Please don't merge yet, I'm still polishing...

### CODE REVIEW

**Comment by mraible** [comment]
This is now ready to merge.

**Comment by mraible** [comment]
@jdubois Can you please merge this? I don’t have permission.

**Comment by jdubois** [comment]
Oh yes of course!
BTW we also need to release a new JHipster Registry version with this new configuration

**Comment by mraible** [comment]
@jdubois I upgraded JHipster Registry in https://github.com/jhipster/jhipster-registry/pull/334.

**Comment by jdubois** [comment]
Yes but I didn't release a new version, as it doesn't work with the docker-compose sub-generator.
I did update to the new configuration, but it fails with a 404 error on /login
I need to fill a proper ticket for that.

**Comment by mraible** [comment]
That sounds like the client needs to be updated to point to /authorize. Sorry I can’t fix; I only have my phone right now.

**Comment by jdubois** [comment]
Yes, same for me! It's not urgent, it works with the older release

**Pull request merged**
