### PR TITLE
Updated Main Routing Filename

### PR DESCRIPTION
**Pull request by mzack5020**
The most up-to-date routing filename is now: app-routing.module.ts instead of app.route.ts. See the example in [Angular documentation](https://angular.io/guide/router)

### CODE REVIEW

**Comment by mzack5020** [comment]
@jdubois @deepu105 Not sure how to go about assigning reviewers but this is a relatively small change. I'm excited as this is one of my first major PRs on an established repo. Looking forward to any feedback!

**Comment by pascalgrimaud** [comment]
thanks a lot for your PR @mzack5020

**Comment by mzack5020** [comment]
Thanks for the prompt response. Excited to contribute to such a robust project, even if it's only slightly :)

**Comment by pascalgrimaud** [comment]
**all** contributions are welcome, little or big
that's the power of Open Source !

**Pull request merged**
