### PR TITLE
SVG , 1024 , face-1024 added

### PR DESCRIPTION
**Pull request by loydjayme25**
i added my design under images -> logo ( face-1024,1024 ) -> svg file ( Main Design )

### CODE REVIEW

**Comment by deepu105** [comment]
Could you please rename the file in this format. `logo-alt-[size].[ext]`

**Comment by loydjayme25** [comment]
example @deepu105  logo-1024 ? how about the svg file ?

**Comment by loydjayme25** [comment]
@deepu105 i renamed the file. pls do check

**Comment by deepu105** [comment]
@loydjayme25 looks good

**Comment by deepu105** [comment]
@jdubois what do you think? we need  to squash though since there are too many commits

**Comment by loydjayme25** [comment]
@deepu105  thank you sir :)

**Comment by jdubois** [comment]
Awesome work, thanks a lot @loydjayme25 !!!

**Pull request merged**
