### PR TITLE
Update documentation for jhipster/generator-jhipster#7120

### PR DESCRIPTION
**Pull request by mraible**
Update docs for https://github.com/jhipster/generator-jhipster/pull/7120

### CODE REVIEW

**Comment by jdubois** [comment]
I'll merge this when JHipster v5 is released

**Comment by mraible** [comment]
I think this should be merged now since it's relevant to our current release (4.14.0).

**Comment by jdubois** [comment]
Oh then it would need to be also cherry-picked to the v4 maintenance branch. Let me have a look.

**Comment by jdubois** [comment]
Argh you have several commits, so that should be several cherry picks I guess - @mraible could you have a look at merging this yourself?

**Comment by mraible** [comment]
@jdubois There's only one commit here for the documentation. I'm just asking for this PR to be merged, not the others.

**Comment by jdubois** [comment]
Oh OK @mraible - I thought you wanted me to merge the code in v4 branch (but hopefully v5 will be out soon!)

**Comment by charfeddine12** [comment]
is there any methods or useful tutos to update or change admin dashbord with jhipster 4 ?

**Pull request merged**
