### PR TITLE
Create 006_tips_enable cross_origin_requests

### PR DESCRIPTION
**Pull request by tomcgn**
as requested from @deepu105

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks!!!! I'll review this next week.

**Comment by gmarziou** [comment]
I think the part about the CORS headers filter is a bit hacky as it modifies an existing filter CsrfCookieGeneratorFilter which has a different purpose. It has 2 drawbacks:
- it violates single responsibility principle
- it makes updating jhipster alit bit more difficult

**Comment by tomcgn** [comment]
Hello Gael,
Thanks for the feedback.
You're right. I had a suspect that it might be so. Unfortunately I have
not enough understanding of the exisiting Filters  and CSRF in general
to propose a better solution.

Do you have an idea how to achieve the same goal: accessing the jhipster
api from an independent, 3rd party website / JS client?
Then, apart from the valid design principles reasons you pointed out: do
you see security aspects undermined with the current approach?

Kind regards,

Thomas


Am 07.08.2015 um 17:51 schrieb Gaël Marziou:

**Comment by gmarziou** [comment]
Don't worry Thomas, in fact I deleted my comment few hours after I wrote it because it was not so relevant and also when JHipster will support Spring Boot 1.3 we will rewrite this tip to use new annotation @CrossOrigin introduced in Spring 4.2.

**Pull request merged**
