### PR TITLE
Add SwissDev Java jobs as user

### PR DESCRIPTION
**Pull request by Vrq**

### CODE REVIEW

**Comment by Vrq** [comment]
@pascalgrimaud would you mind having a look? 🙈

**Comment by jdubois** [comment]
There is no hard rule on the companies we showcase here, but usually we only put "well known" and big companies. And I'm sorry, but I have never heard of https://swissdevjobs.ch/ so I would rather have your company in the "normal" list.
This list is important to us, as we want to show we have those big companies using JHipster.

**Comment by Vrq** [comment]
Hi @jdubois, I totally understand.
You can be assured that we might not be a world-wide brand but we are quite popular in the developer space, for example, if you search on Google for: Switzerland developer jobs
we are the top 1 result.
I think it might be good for you to showcase that you are also popular among the developer related companies - the final decision is of course up to you :)

**Comment by Vrq** [comment]
@jdubois @pascalgrimaud, what's your take? Mind supporting a fellow developer?

**Comment by Vrq** [comment]
@vivekmore thanks! Commited your suggestions :)

**Comment by deepu105** [comment]
Is this website built with JHipster?

**Comment by Vrq** [comment]
@deepu105 we use it for our microservices, the main website grew from a simple CRA project.

**Comment by Vrq** [comment]
@pascalgrimaud don't want to hurry, but could we merge it, since all checks look green? 😃

**Comment by pascalgrimaud** [comment]
@Vrq : can you solve the conflicts plz?

**Comment by Vrq** [comment]
@pascalgrimaud should be fixed now 💥

**Comment by pascalgrimaud** [comment]
Then, let's accept this.
Sorry for taking so long, and congrats for your 1st contribution :)

**Comment by Vrq** [comment]
Thanks! :)

**Pull request merged**
