### PR TITLE
Add MariaDB support

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Plz remember don't merge now => only for the next release

### CODE REVIEW

**Comment by jdubois** [comment]
@pascalgrimaud isn't this included in the next version now, do we need to add this tip?
I'm merging it anyway, we can still remove it afterwards

**Comment by pascalgrimaud** [comment]
Yes my PR was merged, it is already in master!

**Comment by jdubois** [comment]
Sorry I'm not sure I understand, should this tip be merged for the next release? I already did it in my branch (preparing the next release) but I can rollback

**Comment by pascalgrimaud** [comment]
Yes, need to be merged.
It's not a tip, it's an update of current documentation

**Comment by jdubois** [comment]
OK then!

**Pull request merged**
