### PR TITLE
optimize css & images

### PR DESCRIPTION
**Pull request by deepu105**
Seems like the CSS and source SASS files went out of sync due to direct editing of css files. Synced them and add the optimize script on package.json

When making style changes edit the `css/scss/*.scss` files and run `npm run optimize`

### CODE REVIEW

**Comment by ruddell** [comment]
When I run `npm run optimize` locally only Mac (tried with both Node v8.14.0 and v14.15.1), I get a `MaxBufferError` error. This is after checking out your PR with no other changes.

```
[12:38:55] Using gulpfile ~/Contrib/jhipster.github.io/gulpfile.js
[12:38:55] Starting 'sass'...
[12:38:55] Finished 'sass' after 86 ms
[12:38:56] Using gulpfile ~/Contrib/jhipster.github.io/gulpfile.js
[12:38:56] Starting 'images'...
[12:38:56] Starting 'min-img'...
[12:38:56] Starting 'min-images'...
[12:38:56] Starting 'min-company-logo'...
[12:39:00] gulp-imagemin: Minified 1 image (saved 13 B - 0.1%)
[12:39:00] Finished 'min-company-logo' after 4.25 s
[12:39:11] gulp-imagemin: Minified 0 images
[12:39:11] Finished 'min-img' after 15 s
[12:39:26] 'min-images' errored after 30 s
[12:39:26] MaxBufferError in plugin "gulp-imagemin"
Message:
    stdout maxBuffer exceeded
Details:
    bufferedData: GIF89a���<0-33223333342162142343322424692045838=?>?]^i'z/] N&&J)'F+)C-*@.+R$#X!![  ]  _!
......
```

**Comment by deepu105** [comment]
Thats strange. Can you try running gulp sass and gulp images task
seperately? It ran fine for me on Linux

**Comment by pascalgrimaud** [comment]
With my configuration:

```
20:01:32 in projects/jhipster/jhipster.github.io on  pr/1085 [!] took 2s 
➜ node -v         
v14.15.4

20:02:42 in projects/jhipster/jhipster.github.io on  pr/1085 [!] 
➜ npm -v          
6.14.10

```

Just tried it, and I got a lot of warning:
- git checkout pr/1085
- npm ci
- npm run optimize

```
[20:01:11] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:11] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:12] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:12] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:12] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:12] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:13] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:13] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:13] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:13] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:13] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:14] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:14] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:14] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:14] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:14] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:14] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:14] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:15] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:15] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:15] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:15] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:15] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:15] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:15] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:15] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:16] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:16] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:16] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:16] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:16] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:16] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:16] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:16] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:17] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:18] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:18] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:18] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:18] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:18] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:19] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:19] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:19] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:20] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:20] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:20] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:20] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:20] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:20] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:21] gulp-imagemin: Couldn't load default plugin "gifsicle"
[20:01:27] gulp-imagemin: Minified 4 images (saved 322 kB - 35.9%)
[20:01:27] Finished 'min-images' after 27 s
[20:01:27] Finished 'images' after 27 s

20:01:27 in projects/jhipster/jhipster.github.io on  pr/1085 [!] took 29s 
```

**Comment by pascalgrimaud** [comment]
I got these warning during `npm ci` too:

```
20:04:12 in projects/jhipster/jhipster.github.io on  pr/1085 [!] took 5s 
➜ npm ci     
npm WARN prepare removing existing node_modules/ before installation

> node-sass@4.14.1 install /home/pgrimaud/projects/jhipster/jhipster.github.io/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/pgrimaud/.npm/_cacache/node-sass/4.14.1/linux-x64-83_binding.node

> node-sass@4.14.1 postinstall /home/pgrimaud/projects/jhipster/jhipster.github.io/node_modules/node-sass
> node scripts/build.js

Binary found at /home/pgrimaud/projects/jhipster/jhipster.github.io/node_modules/node-sass/vendor/linux-x64-83/binding.node
Testing binary
Binary is fine

> optipng-bin@6.0.0 postinstall /home/pgrimaud/projects/jhipster/jhipster.github.io/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> mozjpeg@6.0.1 postinstall /home/pgrimaud/projects/jhipster/jhipster.github.io/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> gifsicle@5.0.0 postinstall /home/pgrimaud/projects/jhipster/jhipster.github.io/node_modules/gifsicle
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found


    at /home/pgrimaud/projects/jhipster/jhipster.github.io/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)

> fsevents@1.2.7 install /home/pgrimaud/projects/jhipster/jhipster.github.io/node_modules/fsevents
> node install

added 1018 packages in 5.826s
```

**Comment by ruddell** [comment]
The `sass` step works as expected, but the `images` step still fails.  It's related to one of the GIFs, if I remove that extension from the gulp config it works.

One thing I don't like is that running the `images` task re-minifies the following images for me:
```
companies-using-jhipster/images/xebialabs.jpg
images/jhipsteruml_otherEntityFieldMM.jpeg
images/jhipsteruml_otherEntityFieldOM.jpeg
images/sticker_on_laptop.jpg
images/sticker_on_laptop_thumbnail.jpg
```
If you re-run the ` images` task it reduces their size even more.

**Comment by deepu105** [comment]
Well the image minification is not a big deal we can skip that whats
important is to run the sass task when styles are updated

**Comment by mraible** [comment]
@deepu105 Can you please fix conflicts?

**Comment by deepu105** [comment]
Damn totally forgot to merge this

**Comment by deepu105** [comment]
I'll fix and merge tomorrow

**Comment by deepu105** [comment]
I removed the images, lets not worry about them for now

**Pull request merged**
