### PR TITLE
Update to use new website

### PR DESCRIPTION
**Pull request by mraible**
From https://jhipster-website.netlify.app

### CODE REVIEW

**Comment by mraible** [comment]
I tried to update the preview feature on Netlify to run `npm run build`, but it fails with the following error:

```
10:46:39 AM: $ npm run build
10:46:39 AM: > jhipster-website@2.0.0 build /opt/build/repo
10:46:39 AM: > docusaurus build
10:46:39 AM: file:///opt/build/repo/node_modules/@docusaurus/core/bin/docusaurus.mjs:31
10:46:39 AM: process.env.BABEL_ENV ??= 'development';
10:46:39 AM:                       ^^^
10:46:39 AM: SyntaxError: Unexpected token '??='
10:46:39 AM:     at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)
10:46:39 AM:     at async link (internal/modules/esm/module_job.js:67:21)
```

**Comment by mraible** [comment]
@SvMak It looks like there's a plugin that generates the sitemap. Can you please compare the existing sitemap with the new one to ensure they have the same URLs?

**Comment by SvMak** [comment]
> @SvMak It looks like there's a plugin that generates the sitemap. Can you please compare the existing sitemap with the new one to ensure they have the same URLs?

Yes, the sitemap is generated automatically.

Ok I'll compare site maps.

**Comment by SvMak** [comment]
> > @SvMak It looks like there's a plugin that generates the sitemap. Can you please compare the existing sitemap with the new one to ensure they have the same URLs?
> 
> Yes, the sitemap is generated automatically.
> 
> Ok I'll compare site maps.

Screenshot 2024-07-22 at 20 09 06

https://www.jhipster.tech/jdl/applications
https://www.jhipster.tech/jdl/deployments
https://www.jhipster.tech/jdl/entities-fields
https://www.jhipster.tech/jdl/enums
https://www.jhipster.tech/jdl/getting-started
https://www.jhipster.tech/jdl/intro
https://www.jhipster.tech/jdl/options
https://www.jhipster.tech/jdl/relationships
https://www.jhipster.tech/jdl/troubleshooting

in the new sitemap these URLs have a trailing slash

https://www.jhipster.tech/tips/004_tip_using_ms_sql_server.html

the old sitemap only contains this URL and /tips/

tips has redirects in redirects.config.ts

release pages also have html extension
all urls has redirect from html extension in redirects.config.ts

https://www.jhipster.tech/presentation - deleted

https://www.jhipster.tech/cn/ - china website version

https://www.jhipster.tech/association/ - this page is lost, I need to add it

and the old sitemap is aliased www, would you like to add www to new sitemap?
https://jhipster.tech -> https://www.jhipster.tech

**Comment by mraible** [comment]
If I compare https://deploy-preview-1357--jhipster-site.netlify.app/association/ to https://www.jhipster.tech/association/, I see a few differences.

1. The new website just has "The" instead of "The association" as a header.
2. The old website shows a link icon when you mouseover headings. The new website shows an anchor tag when you mouseover headings. 
3. The new website is missing words from headings.

**Comment by SvMak** [comment]
> If I compare https://deploy-preview-1357--jhipster-site.netlify.app/association/ to https://www.jhipster.tech/association/, I see a few differences.
> 
> 1. The new website just has "The" instead of "The association" as a header.
> 2. The old website shows a link icon when you mouseover headings. The new website shows an anchor tag when you mouseover headings.
> 3. The new website is missing words from headings.

1. Could you tell me where, I can't find it
2. Yes, but their behavior is the same. An anchor tag is a direct link to the heading
3. An example would be greatly appreciated

**Comment by SvMak** [comment]
> > If I compare https://deploy-preview-1357--jhipster-site.netlify.app/association/ to https://www.jhipster.tech/association/, I see a few differences.
> > 
> > 1. The new website just has "The" instead of "The association" as a header.
> > 2. The old website shows a link icon when you mouseover headings. The new website shows an anchor tag when you mouseover headings.
> > 3. The new website is missing words from headings.
> 
> 1. Could you tell me where, I can't find it
> 2. Yes, but their behavior is the same. An anchor tag is a direct link to the heading
> 3. An example would be greatly appreciated

I'll be happy to fix it if you provide more information about the issues.

**Comment by mraible** [comment]
> re: association page

If you compare the headings b/w old and new you'll see they don't match. The current one displays a link icon when you mouse over a heading, the new one is missing words in the headings and there is no link icon.

> in the new sitemap these URLs have a trailing slash

I'd prefer there is no trailing slash. Is it possible to change this behavior? If not, do we need to do redirects? 

@jdubois Can we test this in a staging environment that mimics production to see?

> release pages also have html extension

Can we make it so the old URLs with the extension work and default to no extension for the future?

**Comment by SvMak** [comment]
> I'd prefer there is no trailing slash. Is it possible to change this behavior? If not, do we need to do redirects?

Would you like there to be no trailing slash for all links or just for some links?

> Can we make it so the old URLs with the extension work and default to no extension for the future?

I'll check it out and let you know

**Comment by SvMak** [comment]
> If you compare the headings b/w old and new you'll see they don't match. The current one displays a link icon when you mouse over a heading, the new one is missing words in the headings and there is no link icon.

jhipster-links

Could you take a screenshot of the missing words, I think I checked the headers and overall I didn't change anything on the page

**Comment by SvMak** [comment]
Latest changes #1365 

Screenshot 2024-07-25 at 17 49 12
The current difference

- routes with .html -> /{route_name}.html
- routes with trailing slash -> /{route_name}/
- routes without trailing slash -> /{route_name}

> Can we make it so the old URLs with the extension work and default to no extension for the future?

Screenshot 2024-07-25 at 17 54 59

Yes, slug can be without trailing slash /2024/06/24/jhipster-release-8.6.0 or with trailing slash /2024/06/24/jhipster-release-8.6.0/ or with .html ext /2024/06/24/jhipster-release-8.6.0.html

**Comment by mraible** [comment]
@SvMak Thanks for making the URLs match. Is there anything else we should do before pushing this to a staging environment?

**Comment by SvMak** [comment]
@mraible 

1. What's about "association" page? Can I add a direct link to the sidebar navigation?
2. [pr](https://github.com/jhipster/jhipster.github.io/pull/1361) is it still relevant?

**Comment by mraible** [comment]
I believe a direct link to the association is fine. Is there a PR for this or has it already been integrated? 

I believe the translations can be removed. Please confirm @pascalgrimaud @jdubois.

**Comment by SvMak** [comment]
@mraible Latest sitemap changes https://github.com/jhipster/jhipster.github.io/pull/1357#issuecomment-2250796903 are in https://github.com/jhipster/jhipster.github.io/pull/1365, could you merge it please?

**Comment by pascalgrimaud** [comment]
@mraible : yes, I suggested to remove the links to CN / JP translated websites, as it's not maintained
@jdubois suggested to contact and ping the authors first

**Comment by jdubois** [comment]
Hello, we have 2 official translations, one for Chinese and one for Japanese. They both make a lot of sense: those countries have a lot of Java developers, and it's much easier to understand in your own language (I wrote a book on Spring in French for this exact reason!).
They both seem to be pretty active, and we should integrate them: at first I wanted to ping both project's owners, but I see they have a number of contributors, so in order to include everyone and do everything in public, I'm going to create one issue in each repo, and link them to this ticket. They should appear below this message in the next minutes.

**Comment by SvMak** [comment]
I can still:

1. Add links to old versions to the language switcher
2. Hide the language switcher (instead of deleting it)

Until the translation issue is resolved

**Comment by jdubois** [comment]
Can we keep the language switcher, at least for a few months? It’s all volunteer work, so it’s normal that things take time.

**Comment by SvMak** [comment]
> Can we keep the language switcher, at least for a few months? It’s all volunteer work, so it’s normal that things take time.

Of course, to speed up the release of the new website, I propose one of the options:

1. Add links to old versions to the language switcher(demo in WhatsApp group)
2. Hide the language switcher

Instead of removing all the functionality that was done in #1361 

We can remove the translation functionality at any time if needed

**Comment by mraible** [comment]
@SvMak I added the 8.7.0 release notes in https://github.com/jhipster/jhipster.github.io/pull/1357/commits/d2f2b1b2f2916bfb8eee87e9277e27fa46e5bf84. However, it seems this broke the build. I just copied the file, renamed the extension to `mdx`, and updated the front matter. Is there something I missed?

**Comment by SvMak** [comment]
> @SvMak I added the 8.7.0 release notes in [d2f2b1b](https://github.com/jhipster/jhipster.github.io/commit/d2f2b1b2f2916bfb8eee87e9277e27fa46e5bf84). However, it seems this broke the build. I just copied the file, renamed the extension to `mdx`, and updated the front matter. Is there something I missed?

@mraible Yes, for old website internal links you must use {{ site.url }}, for new website you must use just relative path:

Screenshot 2024-08-28 at 08 08 19

I made a fix in #1368

**Pull request merged**
