### PR TITLE
JDL relationship clarification

### PR DESCRIPTION
**Pull request by tuxetuxe**
I could only figure it out by reading the Jhipster-UML code :/

### CODE REVIEW

**Comment by jdubois** [comment]
@MathieuAA do you confirm?

**Comment by MathieuAA** [comment]
For me it's clear enough, but I'll have a more inquisitive look.

**Comment by MathieuAA** [comment]
My bad, I thought there was a problem with the implementation.
The documentation doesn't explicitely (there's only one *hidden* example) say how it can be done with the UML editors, so I guess you can mege it, yes. I'll make a PR with the changes for the UML editors.

**Comment by MathieuAA** [comment]
Update, and a big sorry. You can merge it but it is already explained in the documentation how to perform such a thing, in the very beginning of the doc right [here](https://jhipster.github.io/jhipster_uml.html#umlfile).

**Pull request merged**
