### PR TITLE
added jdl entity field inline javadoc example

### PR DESCRIPTION
**Pull request by kaidohallik**
can be merged after jhipster/jhipster-core#89 is fixed
possible fix in PR jhipster/jhipster-core#90

### CODE REVIEW

**Comment by MathieuAA** [comment]
@jdubois you shouldn't have merged it. There is no issue.

**Comment by MathieuAA** [comment]
@jdubois the example is wrong here.

**Comment by jdubois** [comment]
Oups sorry @MathieuAA -> I'm reverting it

**Comment by jdubois** [comment]
Reverted in https://github.com/jhipster/jhipster.github.io/commit/b43112ebd3152736900c50e040fae907374f0c97

**Comment by MathieuAA** [comment]
I didn't have time this morning to tell you about it, all my fault. 

Le 30 novembre 2016 10:13:00 GMT+01:00, Julien Dubois <notifications@github.com> a écrit :
>Oups sorry @MathieuAA -> I'm reverting it
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster.github.io/pull/358#issuecomment-263821523

-- 
Mathieu ABOU-AICHI

**Pull request merged**
