### PR TITLE
Added tip 26: upgrade jhipster_upgrade branch

### PR DESCRIPTION
**Pull request by tibistibi**
I use these commands to upgrade the jhipster upgrade branch, i think it is worth sharing.

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks @tibistibi !! There definitely is a lot of documentation and work to do on the upgrade process -> I think this shouldn't be a tip, but directly included in the "upgrade" documentation, WDYT? Would you be OK to move your tip there?

**Comment by tibistibi** [comment]
I think many will need this so if thats a better place i'm al for it ;)

**Comment by tibistibi** [comment]
i can move it, where do i need to look?

**Comment by PierreBesson** [comment]
@tibistibi I'm nous sure but couldn't your workflow be automated as part of jhipster upgrade itself ?

**Comment by tibistibi** [comment]
@PierreBesson i do not know, not sure how it works now.

**Comment by tibistibi** [comment]
@jdubois added it there (too)

**Comment by jdubois** [comment]
Thanks @tibistibi - as #704 is merged I'm closing this one

**Pull request closed without merging**
