### PR TITLE
Fixed instructions about how to customise Bootstrap working around wiredep

### PR DESCRIPTION
**Pull request by gmarziou**
Fixed instructions about how to customise Bootstrap taking into account the wiredep grunt task.
As I don't know gulp, I did not cover it but I suppose that the wiredep task configuration should have also a way to exclude files.

### CODE REVIEW

**Comment by andidev** [comment]
This looks really good, great work!

Considering the gulpchanges needed to disable the wiredep of bootstrap-sass it should look like this
```
gulp.task('wiredep:app', function () {
    ...
    gulp.src('src/main/scss/main.scss')
    .pipe(wiredep({
        exclude: [/angular-i18n/, /swagger-ui/, /bootstrap-sass\/assets\/stylesheets/]],
    ...
```

**Comment by gmarziou** [comment]
Thanks I committed this change.

**Comment by jdubois** [comment]
Can you have a look at the merge conflict?

**Comment by gmarziou** [comment]
As it's the first time I merge conflicts on github, be careful when accepting.

**Pull request merged**
