### PR TITLE
Protecting Kibana with Apache (Basic Authentication)

### PR DESCRIPTION
**Pull request by raiden0610**
Section added in the monitoring page

Tell me what you think about that, feedback are welcomed 😀

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Ping @PierreBesson, as he's the boss on this part

**Comment by PierreBesson** [comment]
Personally I would have done it with nginx ;-).
@raiden0610  Can you move it to the tips section and add some comments that this was contributed by you.
If I have the time I might add some info on how to do it with nginx. I have wanted to do it for some time.

**Comment by raiden0610** [comment]
@PierreBesson I have more experience with Apache hehe 😄 
Ok, I'll do it.

**Comment by raiden0610** [comment]
I have a problem, It's not really related to this pull request but when I tried to access to /tips it trigger a loop of redirect.
the command I use : bundle exec jekyll serve
I didn't add the problem with the monitor page.
I try both on windows and on MacOS.
My version of Jekyll is 3.6.2

**Comment by jdubois** [comment]
I'm also running it with `bundle exec jekyll serve` - it works today, but that's often broken.
We're supposed to also have the Docker image working but there was a ticket yesterday on it: https://github.com/jhipster/generator-jhipster/issues/7067
Don't worry too much: focus on the text, I'll correct the design if necessary

**Comment by PierreBesson** [comment]
LGTM, @jdubois please merge.

**Pull request merged**
