### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by mshima**

### CODE REVIEW

**Comment by mshima** [comment]
Should gcloud, openshift and others deployments be removed or add a warning that the generator have been removed?

**Comment by DanielFran** [comment]
> Should gcloud, openshift and others deployments be removed or add a warning that the generator have been removed?

Better to remove

**Comment by pascalgrimaud** [comment]
Not sure about removing these pages, as it's not good for SEO
That's why there are still other old pages

**Comment by mraible** [comment]
I'm not sure we should be concerned about SEO. It's not like we have a lot of competition for terms like "JHipster GAE." If we do, I think that's a good thing.

**Comment by atomfrede** [comment]
:facepalm: I should have looked at the existing PRs before doing https://github.com/jhipster/jhipster.github.io/pull/1328

**Review by atomfrede — APPROVED** [review]

**Comment by atomfrede** [comment]
Let's merge this first in my other PR the heroku part is the most important thing.

**Pull request merged**
