### PR TITLE
Update API-First doc for openapi-generator

### PR DESCRIPTION
**Pull request by deepu105**
@cbornet I accidentally merged the PR and hence reverted it and created this PR, hope you don't mind

### CODE REVIEW

**Comment by cbornet** [comment]
No pb 😃

**Comment by cbornet** [comment]
@deepu105 the gradle task name should soon be `openApiGenerate` instead of `openapi` : https://github.com/jhipster/generator-jhipster/pull/7760 . Can you update the PR ?

**Comment by deepu105** [comment]
ok

**Comment by cbornet** [comment]
I'll do another PR for the `openApiGenerate` gradle task name

**Pull request merged**
