### PR TITLE
update gradle sonar command

### PR DESCRIPTION
**Pull request by atomfrede**
This is relevant for https://github.com/jhipster/generator-jhipster/pull/9328 and https://github.com/jhipster/generator-jhipster/pull/9337 so basically a v6 relevant change

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks @atomfrede ! Is this why our code coverage suddenly dropped on https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application ?

**Comment by atomfrede** [comment]
Yes most likely. I think we anticipated that when splitting tests and integration tests with https://github.com/jhipster/generator-jhipster/pull/9173

**Comment by DanielFran** [comment]
@atomfrede For maven can you change to use _"./mvnw -Pprod clean **verify** sonar:sonar"_ instead?
Thanks

**Comment by atomfrede** [comment]
@DanielFran Done

**Comment by DanielFran** [comment]
@atomfrede This should be included in v6. Is it missing something or did you forget to remove the WIP?

**Comment by atomfrede** [comment]
@DanielFran Yes :(

**Comment by atomfrede** [comment]
Wait, something went wrong during rebase.

**Comment by atomfrede** [comment]
@jdubois @pascalgrimaud We should merge this as currently the documentation is not correct

**Comment by pascalgrimaud** [comment]
done ! Thanks @atomfrede !

**Pull request merged**
