### PR TITLE
Update liquibase documentation

### PR DESCRIPTION
**Pull request by fleboulch**
Linked with https://github.com/jhipster/generator-jhipster/pull/20727

### CODE REVIEW

**Comment by fleboulch** [comment]
@DanielFran here is the update of the liquibase documentation

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
@fleboulch Seems OK, but you need to update the date of last changes here: https://github.com/jhipster/jhipster.github.io/pull/1259/files#diff-474dd741e37d9e9fdcc995ce1235325963720b618fb6553622f19dd2a1a0d4b6R9

**Review by DanielFran — CHANGES_REQUESTED** [review]
@fleboulch Seems OK, but you need to update the date of last changes here: https://github.com/jhipster/jhipster.github.io/pull/1259/files#diff-474dd741e37d9e9fdcc995ce1235325963720b618fb6553622f19dd2a1a0d4b6R9

**Comment by fleboulch** [comment]
I change the update date. Thanks

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
Thanks @fleboulch for the contribution

**Pull request merged**
