### PR TITLE
MongoDB cluster documentation

### PR DESCRIPTION
**Pull request by wmarques**
When [this PR](https://github.com/jhipster/generator-jhipster/pull/3301) will be merged, this documentation teaches how to set up a mongoDB replicaset.

### CODE REVIEW

**Comment by wmarques** [comment]
Maybe we should merge this as the PR has been merged on the generator :)

**Comment by pascalgrimaud** [comment]
Mhhh... the documentation would not be sync with the v3.0.0
Maybe merge as soon as there is a new release?

**Comment by wmarques** [comment]
Oh yes right, forgot that we didn't release this yet !

**Comment by jdubois** [comment]
Yes that's why I merge the website only before a release.

**Pull request merged**
