### PR TITLE
Added doc about options in applications

### PR DESCRIPTION
**Pull request by MathieuAA**
Related to https://github.com/jhipster/jhipster-core/issues/399.

Please, do not merge before JCore is released and the PR in the generator is merged **and the generator's version is bumped**.

### CODE REVIEW

**Comment by MathieuAA** [comment]
@pascalgrimaud be ready ;)

**Comment by pascalgrimaud** [comment]
@MathieuAA : is it for the next release of generator-jhipster ? Or can it be merged as soon as you say `go` ?

**Comment by MathieuAA** [comment]
You're right, let's merge it for the next patch/minor version of the generator. I'm preparing JCore right now

**Comment by pascalgrimaud** [comment]
I'm tagging with `next-release` label

**Pull request merged**
