### PR TITLE
update to new gradle logo

### PR DESCRIPTION
**Pull request by jlstrater**
I updated the Gradle elephant logo on your website. I did a simple find/replace so please let me know if I missed any.

### CODE REVIEW

**Comment by jdubois** [comment]
Hey, thanks @jlstrater ! Do you remember meeting at Spring IO?

**Comment by jlstrater** [comment]
Hi Julien, that was quick! Thanks for merging. And, yes I remember. It was in the hallway track on the first day. ;) I hope we can catch up again at another event.

**Comment by jdubois** [comment]
Thanks :-)
If you are available, I can get you a free seat at https://jhipster-conf.github.io/

**Comment by jlstrater** [comment]
😞 Unfortunately, I have another commitment that day.

**Pull request merged**
