### PR TITLE
Add Sinhala and Bulgarian Language to Documentation

### PR DESCRIPTION
**Pull request by SudharakaP**
This adds [Sinhala](https://en.wikipedia.org/wiki/Sinhala_language) and [Bulgarian](https://en.wikipedia.org/wiki/Bulgarian_language) languages to the documentation.

Related to https://github.com/jhipster/generator-jhipster/issues/11563

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Sorry for asking it here @SudharakaP 
Following https://github.com/jhipster/generator-jhipster/pull/11498 : can you add the new Bulgarian language too here ? So it won't be conflict when I'll do the release

What do you think ?

**Comment by SudharakaP** [comment]
> Sorry for asking it here @SudharakaP
> Following [jhipster/generator-jhipster#11498](https://github.com/jhipster/generator-jhipster/pull/11498) : can you add the new Bulgarian language too here ? So it won't be conflict when I'll do the release
> 
> What do you think ?

Done. :smile:

**Comment by pascalgrimaud** [comment]
you're awesome @SudharakaP
really thank you so much

**Comment by SudharakaP** [comment]
> you're awesome @SudharakaP
> really thank you so much

You are welcome. :smile:

**Pull request merged**
