### PR TITLE
rename fisherman to fisher

### PR DESCRIPTION
**Pull request by atomfrede**
* replace all occurences of `fisherman` with `fisher`
* update links

updates https://github.com/jhipster/jhipster-fisher-plugin/issues/17

### CODE REVIEW

**Comment by jdubois** [comment]
@atomfrede you also need to add the redirect from the old pages so we don't get 404 (important for Google Webmaster Tools)

**Comment by atomfrede** [comment]
I did not remove the old page, so it is still there. How do I add a redirect from `fischerman` to `fisher`? Just adding an additional `redirect_from` in the new page? (sorry no jekyll expert)

**Comment by jdubois** [comment]
Yes - otherwise I'll do it, but not until 2 weeks at least

**Comment by jdubois** [comment]
I'm merging and then I'll correct the redirect

**Comment by jdubois** [comment]
Oh you already fixed this, thanks a lot @atomfrede !

**Pull request merged**
