### PR TITLE
Update jhipster_uml.md

### PR DESCRIPTION
**Pull request by MathieuAA**
The UML Designer's section has been updated to include unidirectional relationships.

### CODE REVIEW

**Comment by jdubois** [comment]
@MathieuAA we are currently redesigning the website with @deepu105 and I'm afraid we could lose this change -> this is why I am not merging this yet, so we don't take risks

**Comment by deepu105** [comment]
@jdubois yes plz hold any merge, so that we dont loose anything

Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
Ok =)

**Comment by MathieuAA** [comment]
So... Can I still make PRs, knowing that they wouldn't be merged right away?

**Comment by jdubois** [comment]
Yes, we will merge them afterwards. It's just so we don't forget them.
Le 16 janv. 2016 9:52 PM, "Mathieu ABOU-AICHI" <notifications@github.com> a
écrit :

**Comment by MathieuAA** [comment]
Ok, thanks Julien!

**Comment by MathieuAA** [comment]
That's one hell of a website! Good work guys!

**Comment by jdubois** [comment]
:-)

**Comment by deepu105** [comment]
@jdubois this needs to be merged into the file under pages folder coz i have moved all pages from root into that folder so that its claner and easier to manage

**Pull request merged**
