### PR TITLE
Enforcing HTTPS

### PR DESCRIPTION
**Pull request by seanoreillyza**
Added link for enforcing HTTPS on Cloud Foundry

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks, but the link points to your website, and here I want the documentation on our website. It's a nice tip and I'd love to have on the website, and we would give credit to you (we can also have a link to your website).
The idea is that everything is in the same format, and hopefully in the future we could generate an offline doc with everything.

**Comment by seanoreillyza** [comment]
No problem, I understand. Feel free to incorporate it into the official documentation.

**Comment by jdubois** [comment]
@seanoreillyza oh, you are OK if I copy/paste it? I will add the credit for you and do a link to your site, of course

**Comment by seanoreillyza** [comment]
I don't mind if you copy/paste it.

**Pull request closed without merging**
