### PR TITLE
Update using_elasticsearch.md

### PR DESCRIPTION
**Pull request by cordial**

### CODE REVIEW

**Comment by mraible** [comment]
I believe this might've changed recently. Is this up to date with Spring Boot 2.6.6, @cordial?

**Review by mraible — APPROVED** [review]

**Comment by DanielFran** [comment]
@cordial Can you please rebase the PR to fix issues?

**Review by mraible — APPROVED** [review]

**Comment by mraible** [comment]
I don't see any Elasticsearch configuration changes between JHipster 7 and the [necessary changes for Spring Boot 3](https://github.com/jhipster/generator-jhipster/pull/20001). For this reason, I believe https://github.com/jhipster/jhipster.github.io/pull/1247 might be a better update.

**Comment by saschaszott** [comment]
@mraible , this PR seems to be obvious compared to changes introduced by PR #1247

**Comment by mraible** [comment]
@saschaszott You are correct. Closing.

**Pull request closed without merging**
