### PR TITLE
Added JHipsterDublin

### PR DESCRIPTION
**Pull request by jduggan83**
Created a JHipster meetup group for Dublin. Hope to schedule our first meetup very soon. I welcome any feedback or help you can provide on this. Thanks.

### CODE REVIEW

**Comment by jdubois** [comment]
That's awesome!!!
When you do a meetup, don't hesitate to:

- Do a PR in the "news" section of the home page (lots of traffic)
- Mention @java_hipster on Twitter so I can RT

**Comment by jduggan83** [comment]
Thats great! will do, thanks for the help.

**Comment by jdubois** [comment]
I'm tweeting about it right now

**Comment by jduggan83** [comment]
Brilliant thanks.

**Pull request merged**
