### PR TITLE
add elasticsearch-reindexer

### PR DESCRIPTION
**Pull request by geraldhumphries**
This module will add a service to reindex all rows for each JHipster entity in Elasticsearch. This is useful if any changes have been made to the data outside of the application, like inserting rows using liquibase or migrating data from another DB. It works by reading all the json files from the `.jhipster` folder.

This is a solution I developed for my own project and decided to make it a module. There might be a better solution out there, but so far I haven't found one.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
good job @geraldhumphries you're the first non core dev team to code a module!

**Comment by geraldhumphries** [comment]
Thanks @pascalgrimaud! I used your module generator.

@jdubois we should add the module generator to the "create a module" docs. It was super useful.

**Comment by jdubois** [comment]
Yes, congrats!!

- You need to do more documentation on your README so that people understand what this is all about
- Yes you are correct for the module generator, but I haven't used it myself: can you do a PR for this?

**Comment by geraldhumphries** [comment]
Okay. I've updated the docs to better explain what it is.

@pascalgrimaud how do you want you/your project to be referred to? Right now I have "Pascal Grimaud has created a [module generator](https://github.com/pascalgrimaud/generator-jhipster-module) that will create a sample module to be used as a starting point."

**Comment by pascalgrimaud** [comment]
Oh it will be nice! Give me time to review my code. I did it very fast during happy holidays => so I prefer doing this PR, as soon as it is definitively ready! Is it ok for you @geraldhumphries ?
But it seems to work fine because it works for you!

**Comment by geraldhumphries** [comment]
Yeah, that's fine. I will open an issue/pull request on your project if I have any suggestions for how it can be improved. I will let you create the pull request here when you think it's ready.

**Pull request merged**
