### PR TITLE
Document jib commands everywhere to build docker images

### PR DESCRIPTION
**Pull request by PierreBesson**
To merge only after release.

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks a lot @PierreBesson !

**Comment by jdubois** [comment]
This is a duplicate from #626 but as this is more complete I'm merging this one

**Comment by PierreBesson** [comment]
Sorry @danielpetisme I did not see that you did the work.

**Comment by danielpetisme** [comment]
No pb. I still have time to complete the  hacktoborfest challenge :wink:

**Pull request merged**
