### PR TITLE
Edit me on GitHub take 2

### PR DESCRIPTION
**Pull request by PierreBesson**

### CODE REVIEW

**Comment by jdubois** [comment]
@PierreBesson could you squash all your commits into one? So we can try this easily in prod, and rollback if necessary

**Comment by PierreBesson** [comment]
Sorry I'm in vacation so I can do it only next week. Can you try the github squash feature ?

**Comment by jdubois** [comment]
Oh yes sorry, I forgot about this!
I'm testing right now!!!!!!

**Comment by jdubois** [comment]
And... it's still not good :-(
When you are on mobile and click on the icon on the top left, there is a specific menu appearing. But to close that menu, there's a little cross that's now under the "fork me" banner, so you can't remove that menu and have the normal header.

So I'm reverting :-((((

**Pull request merged**
