### PR TITLE
add edit me on github button

### PR DESCRIPTION
**Pull request by PierreBesson**
Okay last try, this time it's just a super dumb button so I hope it doesn't cause layout issues.

screenshot 2018-11-08 at 18 56 37

I'm also hiding the button on mobile.

### CODE REVIEW

**Comment by jdubois** [comment]
Oh but it's ugly :-(
I'll have a look, maybe it's better to put it in the footer

**Comment by PierreBesson** [comment]
No it's better to put it in the header, the idea is that a maximum of people see it and contribute. BTW it's not that ugly.

**Comment by PierreBesson** [comment]
Thanks for the offer Deepu but let's not lose too much time on this. We have higher priorities.

**Comment by mraible** [comment]
"i'll do it after devoxx" -- @deepu105 

Bump. :)

**Comment by deepu105** [comment]
Ha ha

**Comment by jdubois** [comment]
Be careful as in the header we now have the search box and an advertisement for JHipster Conf 2, so it's already pretty bloated. That's why I still recommend the footer.

**Comment by PierreBesson** [comment]
Yes that's why I initially wanted to add a ribbon like this: https://github.com/jhipster/jhipster.github.io/pull/657
But it would sometimes go over the text of the navbar...

**Comment by SudharakaP** [comment]
I think we can close this issue since I've already done this at https://github.com/jhipster/jhipster.github.io/pull/873

Also, it seems that I don't have ability to close issues or assign labels in this repo. Can you give me permission? :smile:

**Comment by jdubois** [comment]
@SudharakaP let me check why you don't have access, it's probably a team settings

**Comment by SudharakaP** [comment]
@jdubois : Thanks much; you are so quick 👍

**Comment by jdubois** [comment]
OK, that's probably because we wanted to protect the repo, only the "Admin" team has access -> I'm going to give write access to the whole @jhipster/developers teams, use it wisely!

**Comment by pascalgrimaud** [comment]
@jdubois : yes, currently only @deepu105 you and me have write access to this repo. It's because we need to be careful with what needs to be merged here or not and synchronize it with the release

**Comment by pascalgrimaud** [comment]
as asked, let's close this so

**Comment by jdubois** [comment]
Oh yes, @pascalgrimaud you are right, this was open to everybody before in the past, and caused some issues... What do you think, should I remove the permission again?

**Comment by pascalgrimaud** [comment]
No, let's trust our team!
I keep an eye on the merges, no worry :)

**Comment by SudharakaP** [comment]
@jdubois @pascalgrimaud : Please do feel free to remove it if that's more appropriate. I just thought it's permissions issue I have. 😄

**Pull request closed without merging**
