### PR TITLE
Documentation: improve punctuations and embeded code

### PR DESCRIPTION
**Pull request by qmonmert**
Improve punctuations and embeded code on the website

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I love this kind of PR.
Thanks a lot @qmonmert :)

**Comment by qmonmert** [comment]
@pascalgrimaud 😄

**Comment by jdubois** [comment]
I love this too! Sorry as those were all my fault probably 😭
And congrats @qmonmert for your current triathlon! Your VO2 Max is incredible!! 🏊‍♂️🚵‍♂️🏃‍♂️

**Comment by qmonmert** [comment]
Thanks @jdubois 😉

**Pull request merged**
