### PR TITLE
add JDL-studio link

### PR DESCRIPTION
**Pull request by deepu105**
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/nN4_XUmjzOY/_9ZYWi9LEgAJ

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@deepu105 you are impressive ! :open_mouth:

**Comment by deepu105** [comment]
@MathieuAA can you make a small change in your JDL flow to remove any lines starting with # before sending to peg parser?

**Comment by MathieuAA** [comment]
@deepu105 In the grammar file you mean? or in the JDL file?

**Comment by deepu105** [comment]
@no preferably before you pass the JDLfile to peg parser, but if its not straightforward the may be in the peg syntax you can define # also to be similar to // comment

**Comment by deepu105** [comment]
@MathieuAA btw do you think its feasible to parse XMI to JDL?

**Comment by deepu105** [comment]
updated http://hipster-labs.github.io/JDL-studio/ to have a download button to download JDL as a `.jh` file

**Comment by jdubois** [comment]
I've just tested it and it's really incredible!
@Deepu don't you want to host this on the main jhipster.github.io site?

On Wed, Feb 17, 2016 at 12:13 PM, Deepu K Sasidharan <
notifications@github.com> wrote:

> updated http://hipster-labs.github.io/JDL-studio/ to have a download
> button to download JDL as a .jh file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/jhipster.github.io/pull/200#issuecomment-185157766>
> .
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by MathieuAA** [comment]
I'm really against changing the JDL grammar to suit this need. I believe in separation of concerns and I think you'd be better off detecting the '#' char somewhere in your code and dealing with it accordingly.

To "translate" XMI into JDL, you'd have to parse the XMI (like we do), and then convert it back to JDL (we don't do that because we don't need to, but it would be quite easy I believe).

Finally, I suggest you directly require JHipster UML as a dependency (Carl did the work some time ago).

**Comment by deepu105** [comment]
@MathieuAA I already detect the `#` and process that and Im not asking to change the JDL grammer, Im just asking you to ignore '#' if you encounter while processing as people could copy paste with `#` causing error. If you really dont want to do that then I would have to think of some workaround.

and for conversion, yes we dont have to do that in JUML but when we are providing an editor that would be a nice option to import XMI and continue working on it.

Since its a webapp adding Jhipster-UML as a direct dependency would require to use npm and browserify, ill take look when I have time

@jdubois If you are Ok then I can transfer this to Jhipster organisation so that URL will become `jhipster.github.io/JDL-studio/`

**Comment by MathieuAA** [comment]
@deepu105 indeed it would be! Currently, when the parsing's finished for an XMI file, we generate a [parsed data model](https://github.com/jhipster/jhipster-uml/blob/master/lib/data/parsed_data.js) that is filled with the interesting stuff. So it would be quite easy.

Unfortunately, ignoring '#' would mean to change the grammar, unless I don't see when the '#' char would appear.

**Comment by cbornet** [comment]
@deepu105 could you also add an "upload" button ?
@MathieuAA do you think we could have a way to pass the entire definition to jhipster-uml by command line ? This way, there could be a "copy command to clipboard" on the studio.

**Comment by MathieuAA** [comment]
@cbornet by entire definition, do you mean a JDL file's content?

**Comment by cbornet** [comment]
@MathieuAA yup ! Something like the current "share link"

**Comment by MathieuAA** [comment]
@cbornet the problem is to pass a JDL file to JHipster UML. Fortunately, this has already been solved (by passing the file's name). Wouldn't there be a way to:
  1. Save to a file first,
  2. And use JHipster UML to do some good ol' magic.

?

**Comment by cbornet** [comment]
@MathieuAA the steps you describe are currently possible with the studio but it has more manual steps.
Currently you:
1. click on download
2. choose a location
3. enter your command in the console (or get it from history if you saved the file in the same location)
If we could send the JDL content as a command line arg, then the steps would be:
1. click on "copy to clipboard"
2. paste in the console
3. press enter
--> faster

**Comment by MathieuAA** [comment]
What I had in mind was more automatic: you don't actually have to create a file manually. I believe it could be done with some tweaking.

**Comment by deepu105** [comment]
@MathieuAA I think it should be possible to ignore that before sending to peg so that grammar doesn't have to change, coz Im doing that from studio, Im using your peg parser as it is, let me take a look at JUML code

**Comment by deepu105** [comment]
@jhipster/developers plz feel free to PR if you have any interesting stuff in mind of if you want to do anything from below

my current todos in order of priority:

- more syntax highlighting for:
  - attribute Types
  - validation keywords
- autocompletion for keywords, types and entered object names
- add floating buttons to insert entity|relationship|enum template blocks
- import JDL from file
- A light theme switcher to have original nomnoml theme
- ability to convert XMI to JDL if possible
- switch to SVG from canvas if possible so that we can do some drag and drop stuff easily

**Comment by deepu105** [comment]
@jdubois shall I move this to jhipster org?

**Comment by jdubois** [comment]
Yes I'd love to have this "official"

**Comment by deepu105** [comment]
Ok, ill first create a test repo and see if sub context works in jekyl and
will move it accordingly

**Comment by deepu105** [comment]
@jdubois seems I dont have access to create or transfer repo to Jhipster. Can you plz create a test-repo in Jhipster and give me admin access to it?

**Comment by jdubois** [comment]
Yes, I'll have a look at this tomorrow morning

**Comment by deepu105** [comment]
have added some cool auto brackets and autocomplete of all JDL keywords as well as words in the current buffer check it out :)

code mirror is awesome

**Comment by deepu105** [comment]
the repo has been moved to jhipster org https://github.com/jhipster/jdl-studio

**Comment by deepu105** [comment]
@jdubois are you ok with this or do you want any change?

**Comment by jdubois** [comment]
It's merged and I added links to the studio in the entities and relationship pages, so more people are aware of it

**Comment by deepu105** [comment]
nice

Thanks & Regards,
Deepu

**Pull request merged**
