### PR TITLE
eclipse: update screen folder

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Tested with latest Eclipse Neon.
The instruction are still correct. So I only updated the screenshot
Hope you are ok, my OS is ubuntu so the selected folder is now orange!

Fix https://github.com/jhipster/generator-jhipster/issues/4201

### CODE REVIEW

**Comment by jdubois** [comment]
Argh we're doing the same thing at the same time :-(
I just commited this also!

**Comment by jdubois** [comment]
OK mine is better, as I also changed the text, see https://github.com/jhipster/jhipster.github.io/commit/70971c2957d851f36ec25f2fd94d3f52fed7b6e5

**Comment by pascalgrimaud** [comment]
ahah, I admit your screen is better :)
It was an easy PR just before going to bed

**Comment by jdubois** [comment]
Yes, same for me :-)

**Pull request closed without merging**
